### ISSUE TITLE
Missing or invalid $config array

### ISSUE THREAD

**Issue by davideprevosto** [backyardwp/framework#3]
Hello,

I am getting an error about the configurations file.

As per instructions I have created a config folder and a generic "plugin.php" file.

```
<?php

return [
    'my_key' => 'my_value',
];
```

but I am facing into this:

```
Fatal error: Uncaught Configula\Exception\ConfigLoaderException: Missing or invalid $config array in file: /app/wp-content/plugins/test/config/plugin.php in /app/wp-content/plugins/test/vendor/caseyamcl/configula/src/Loader/PhpFileLoader.php:69 Stack trace: #0 /app/wp-content/plugins/test/vendor/caseyamcl/configula/src/Loader/FileLoader.php(84): Configula\Loader\PhpFileLoader->load() #1 /app/wp-content/plugins/test/vendor/caseyamcl/configula/src/Loader/FileListLoader.php(71): Configula\Loader\FileLoader->load() #2 /app/wp-content/plugins/test/vendor/caseyamcl/configula/src/Loader/FolderLoader.php(97): Configula\Loader\FileListLoader->load() #3 /app/wp-content/plugins/test/vendor/caseyamcl/configula/src/ConfigFactory.php(114): Configula\Loader\FolderLoader->load() #4 /app/wp-content/plugins/test/vendor/backyardwp/framework/src/Plugin.php(196): Configula\ConfigFactory::loadPath('/app/wp-content...') #5 /app/wp-content/plugins/test/vendor/backyardwp/framework/src/Plugin.php(95): Backyard\Plugin->loadConfigurationFromFolder(' in /app/wp-content/plugins/test/vendor/caseyamcl/configula/src/Loader/PhpFileLoader.php on line 69
```

Any help on this?

Thank you

**Comment by davideprevosto** [comment]
I suppose I solved using this syntax:

```
<?php

return $config = [
    'my_key' => 'my_value',
];

```

I am not sure I am right 🤔

**Comment by alessandrotesoro** [comment]
Hi @davideprevosto 

Thanks for pointing this out, it's a mistake in the documentation. I'll update it as soon as possible.

The config file requires the `$config` variable. So it needs to be formatted like this:

```php
<?php

$config = [
	'key' => 'value',
];
```

Please note this behaviour may change in the future, until I've tagged v1.
